In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('wuzzuf.csv')
df

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",Posted 27 days ago,48,1 open position,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']"
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",Posted 1 month ago,12,1 open position,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail..."
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",Posted 23 days ago,74,2 open positions,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co..."
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",Posted 1 month ago,50,4 open positions,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']"
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",Posted 3 days ago,32,1 open position,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",Posted 4 days ago,Be the First to Apply,NaN,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito..."
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",Posted 2 days ago,Be the First to Apply,NaN,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie..."
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",Posted 2 months ago,49,1 open position,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas..."
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",Posted 13 days ago,81,1 open position,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']"
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",Posted 15 days ago,15,5 open positions,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D..."

# **Check missing values**

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8983 entries, 0 to 8982
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 8983 non-null   object
 1   Working_Hours         8983 non-null   object
 2   Working_Place         8983 non-null   object
 3   Company               7949 non-null   object
 4   Location              8983 non-null   object
 5   Post_Date             8983 non-null   object
 6   Number_of_Applicants  8982 non-null   object
 7   Number_of_Positions   8668 non-null   object
 8   Experience            8983 non-null   object
 9   Career_Level          8983 non-null   object
 10  Education             8983 non-null   object
 11  Salary                8983 non-null   object
 12  Job_Category          8983 non-null   object
 13  Skills                8983 non-null   object
dtypes: object(14)
memory usage: 982.6+ KB

In [10]:
df["Salary"].unique()

array(['Confidential', '8000 To 12000 EGP Per Month', 'Male', ...,
       '10000 To 15000 EGP Per Month, Transportations - Incentives',
       'Confidential, Overtime Pay: Compensation For Hours Worked Beyond The Standard Working Hours, Typically Paid At A Higher Rate. PTO',
       '10000 To 30000 EGP Per Month, Bonus Commission'], dtype=object)

In [12]:
print(df[df["Salary"] == "Female"])

                                   Title Working_Hours Working_Place  \
16    Administrative Assistant (Gharbia)     Full Time       On-site
38           Accountant - Female - Zaher     Full Time       On-site
86               CEO Executive Assistant     Full Time        Remote
207                  Executive Secretary     Full Time       On-site
238      Cad drafter/Cad Design Engineer     Full Time       On-site
...                                  ...           ...           ...
8777      Customer Advisor / Sales Admin     Full Time        Remote
8790                      Office Manager     Full Time       On-site
8856            Administrative Assistant     Full Time       On-site
8865         Chairman Personal Assistant     Full Time       On-site
8900    Admin Assistant - Office Manager     Full Time       On-site

                                      Company                Location  \
16                                 Aktan Misr  Mahalla Kubra, Gharbia
38                           El-Dahan Company            Zaher, Cairo
86                                    Tritecs            Cairo, Egypt
207                                   olspark          Tanta, Gharbia
238   Green Line For Glass Metal Architecture        Nasr City, Cairo
...                                       ...                     ...
8777                                      NaN            Cairo, Egypt
8790                             TRAVCO GROUP      Sheikh Zayed, Giza
8856                      (kabbani furniture)        New Cairo, Cairo
8865                                AHS Group    6th of October, Giza
8900                                      ARC            Cairo, Egypt

                Post_Date Number_of_Applicants Number_of_Positions  \
16    Posted 2 months ago                   46     1 open position
38     Posted 1 month ago                   21    2 open positions
86    Posted 2 months ago                  199     1 open position
207    Posted 10 days ago                   16     1 open position
238    Posted 29 days ago                   51     1 open position
...                   ...                  ...                 ...
8777   Posted 13 days ago                   35     1 open position
8790  Posted 2 months ago                  206     1 open position
8856  Posted 2 months ago                  163     1 open position
8865   Posted 27 days ago                   85     1 open position
8900   Posted 10 days ago                   94     1 open position

             Experience                             Career_Level  \
16         2 To 5 Years                Experienced (Non-Manager)
38    More Than 2 Years  Entry Level (Junior Level / Fresh Grad)
86         3 To 7 Years                Experienced (Non-Manager)
207        1 To 3 Years  Entry Level (Junior Level / Fresh Grad)
238        0 To 3 Years  Entry Level (Junior Level / Fresh Grad)
...                 ...                                      ...
8777       1 To 4 Years                Experienced (Non-Manager)
8790       6 To 8 Years                Experienced (Non-Manager)
8856       1 To 3 Years  Entry Level (Junior Level / Fresh Grad)
8865  More Than 5 Years                Experienced (Non-Manager)
8900       0 To 2 Years                Experienced (Non-Manager)

              Education  Salary              Job_Category  \
16    Bachelor'S Degree  Female            Administration
38    Bachelor'S Degree  Female        Accounting/Finance
86    Bachelor'S Degree  Female            Administration
207   Bachelor'S Degree  Female  Customer Service/Support
238   Bachelor'S Degree  Female       Creative/Design/Art
...                 ...     ...                       ...
8777  Bachelor'S Degree  Female            Administration
8790  Bachelor'S Degree  Female            Administration
8856      Not Specified  Female            Administration
8865  Bachelor'S Degree  Female            Administration
8900  Bachelor'S Degree  Female            Administration

                                                 Skills
16    ['Administration', 'Secretary', 'Time Manageme...
38    ['Accounting', 'excel', 'Microsoft Office', 'E...
86    ['Administration', 'Business Administration', ...
207   ['Office management', 'Microsoft Office', 'Sec...
238   ['CAD', 'CAD Software', 'Art', 'Design', 'Fine...
...                                                 ...
8777  ['Startup', 'Customer Service', 'Customer Care...
8790  ['Administration', 'English', 'Management', 'M...
8856  ['Admin', 'administrative assistant', 'Microso...
8865  ['Microsoft Office', 'Hospitality', 'Event Pla...
8900  ['Business Administration', 'Communication ski...

[239 rows x 14 columns]

In [13]:
print(df[df["Salary"] == "Male"])

                                       Title Working_Hours Working_Place  \
5                                 Accountant     Full Time       On-site
40           Electrical Maintenance Engineer   Shift Based       On-site
41        Sales & Technical Support Engineer     Full Time       On-site
67                      Maintenance Engineer     Full Time       On-site
77                          Project Director     Full Time       On-site
...                                      ...           ...           ...
8913         Production Maintenance Engineer     Full Time       On-site
8924               IT Infrastructure Manager     Full Time       On-site
8926              Mechanical Design Engineer     Full Time       On-site
8932                      General Supervisor     Full Time       On-site
8943  Electrical Automation Control Engineer     Full Time       On-site

                                          Company               Location  \
5                                 Creative Motion           Maadi, Cairo
40                                            NaN   6th of October, Giza
41    Egyptian Packaging and Plastic Systems Corp          Manial, Cairo
67                  Venus International Free Zone      Alexandria, Egypt
77                          Byld APR Construction           Cairo, Egypt
...                                           ...                    ...
8913                                  Zeta Pharma  Alsadat City, Monufya
8924                                        Roaya           Maadi, Cairo
8926                                          NaN   6th of October, Giza
8932                            Value Development       New Cairo, Cairo
8943                             Beta Electronics            Giza, Egypt

                Post_Date Number_of_Applicants Number_of_Positions  \
5     Posted 2 months ago                  104     1 open position
40     Posted 1 month ago                  122     1 open position
41     Posted 1 month ago                   19    3 open positions
67     Posted 1 month ago                   76    2 open positions
77     Posted 27 days ago                  119     1 open position
...                   ...                  ...                 ...
8913   Posted 1 month ago                   37     1 open position
8924   Posted 11 days ago                  163     1 open position
8926  Posted 2 months ago                   75     1 open position
8932  Posted 2 months ago                    9     1 open position
8943   Posted 1 month ago                  135     1 open position

              Experience                                 Career_Level  \
5           3 To 5 Years                    Experienced (Non-Manager)
40          0 To 3 Years                    Experienced (Non-Manager)
41          2 To 6 Years                    Experienced (Non-Manager)
67          3 To 6 Years                    Experienced (Non-Manager)
77    More Than 15 Years  Senior Management (CEO, GM, Director, Head)
...                  ...                                          ...
8913        5 To 8 Years                    Experienced (Non-Manager)
8924      10 To 15 Years                                      Manager
8926        5 To 7 Years                    Experienced (Non-Manager)
8932        3 To 6 Years                    Experienced (Non-Manager)
8943        2 To 4 Years                    Experienced (Non-Manager)

              Education Salary                                   Job_Category  \
5     Bachelor'S Degree   Male                             Accounting/Finance
40    Bachelor'S Degree   Male                Installation/Maintenance/Repair
41    Bachelor'S Degree   Male                                   Sales/Retail
67    Bachelor'S Degree   Male                Installation/Maintenance/Repair
77    Bachelor'S Degree   Male                                 Administration
...                 ...    ...                                            ...
8913  Bachelor'S Degree   Male  Engineering - Construction/Civil/Architecture
8924  Bachelor'S Degree   Male                        IT/Software Development
8926  Bachelor'S Degree   Male                            Creative/Design/Art
8932      Not Specified   Male  Engineering - Construction/Civil/Architecture
8943  Bachelor'S Degree   Male                Installation/Maintenance/Repair

                                                 Skills
5     ['Accounting', 'Accounting Software', 'excel',...
40    ['Electrical Engineering', 'Engineering', 'Mai...
41    ['Mechatronics', 'Electrical', 'Engineering', ...
67    ['Engineering', 'equipment', 'Maintenance', 'M...
77    ['Civil', 'Civil Engineering', 'Communication'...
...                                                 ...
8913  ['Engineering', 'Maintenance', 'Pharmaceutical...
8924  ['Customer Service', 'Information Technology (...
8926  ['Design', 'AutoCAD', 'CAD', 'Drawing', 'Engin...
8932              ['general supervisor', 'Real Estate']
8943  ['Control panel wiring', 'Electrical control s...

[568 rows x 14 columns]

In [16]:
# take a copy from salary column to get gender column
df['Gender'] = df['Salary']

df["Gender"] = df["Gender"].apply(lambda x: x if x in ["Female", "Male"] else np.nan)

df

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills,Gender
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",Posted 27 days ago,48,1 open position,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']",NaN
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",Posted 1 month ago,12,1 open position,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail...",NaN
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",Posted 23 days ago,74,2 open positions,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co...",NaN
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",Posted 1 month ago,50,4 open positions,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']",NaN
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",Posted 3 days ago,32,1 open position,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",Posted 4 days ago,Be the First to Apply,NaN,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito...",NaN
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",Posted 2 days ago,Be the First to Apply,NaN,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie...",NaN
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",Posted 2 months ago,49,1 open position,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas...",NaN
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",Posted 13 days ago,81,1 open position,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']",NaN
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",Posted 15 days ago,15,5 open positions,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D...",NaN

In [20]:
df["Salary"] = df["Salary"].apply(lambda x: np.nan if x in ["Female", "Male"] else x)
df

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills,Gender
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",Posted 27 days ago,48,1 open position,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']",NaN
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",Posted 1 month ago,12,1 open position,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail...",NaN
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",Posted 23 days ago,74,2 open positions,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co...",NaN
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",Posted 1 month ago,50,4 open positions,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']",NaN
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",Posted 3 days ago,32,1 open position,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",Posted 4 days ago,Be the First to Apply,NaN,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito...",NaN
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",Posted 2 days ago,Be the First to Apply,NaN,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie...",NaN
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",Posted 2 months ago,49,1 open position,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas...",NaN
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",Posted 13 days ago,81,1 open position,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']",NaN
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",Posted 15 days ago,15,5 open positions,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D...",NaN

In [21]:
print(df[df["Salary"] == "Male"])

Empty DataFrame
Columns: [Title, Working_Hours, Working_Place, Company, Location, Post_Date, Number_of_Applicants, Number_of_Positions, Experience, Career_Level, Education, Salary, Job_Category, Skills, Gender]
Index: []

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8983 entries, 0 to 8982
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 8983 non-null   object
 1   Working_Hours         8983 non-null   object
 2   Working_Place         8983 non-null   object
 3   Company               7949 non-null   object
 4   Location              8983 non-null   object
 5   Post_Date             8983 non-null   object
 6   Number_of_Applicants  8982 non-null   object
 7   Number_of_Positions   8668 non-null   object
 8   Experience            8983 non-null   object
 9   Career_Level          8983 non-null   object
 10  Education             8983 non-null   object
 11  Salary                8176 non-null   object
 12  Job_Category          8983 non-null   object
 13  Skills                8983 non-null   object
 14  Gender                807 non-null    object
dtypes: object(15)
memory usage: 1.0+ MB

In [23]:
print(df.isnull().sum())

Title                      0
Working_Hours              0
Working_Place              0
Company                 1034
Location                   0
Post_Date                  0
Number_of_Applicants       1
Number_of_Positions      315
Experience                 0
Career_Level               0
Education                  0
Salary                   807
Job_Category               0
Skills                     0
Gender                  8176
dtype: int64

In [25]:
columns_to_check = ['Company', 'Number_of_Positions', 'Salary']

# Find rows where all selected columns have missing values
missing_rows = df[df[columns_to_check].isnull().all(axis=1)]

missing_rows

Empty DataFrame
Columns: [Title, Working_Hours, Working_Place, Company, Location, Post_Date, Number_of_Applicants, Number_of_Positions, Experience, Career_Level, Education, Salary, Job_Category, Skills, Gender]
Index: []

not preferred to drop rows

In [27]:
df["Number_of_Positions"]

0        1 open position
1        1 open position
2       2 open positions
3       4 open positions
4        1 open position
              ...
8978                 NaN
8979                 NaN
8980     1 open position
8981     1 open position
8982    5 open positions
Name: Number_of_Positions, Length: 8983, dtype: object

In [28]:
df["Number_of_Positions"] = df["Number_of_Positions"].str.extract(r'(\d+)')
df["Number_of_Positions"]

0         1
1         1
2         2
3         4
4         1
       ...
8978    NaN
8979    NaN
8980      1
8981      1
8982      5
Name: Number_of_Positions, Length: 8983, dtype: object

In [32]:
full_time_count = len(df[df["Working_Hours"] == "Full Time"])
print(f"Number of rows with 'Working_Hours' equal to 'Full Time': {full_time_count}")

Number of rows with 'Working_Hours' equal to 'Full Time': 8709

##preferred to drop working hours column

In [35]:
df

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills,Gender
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",Posted 27 days ago,48,1,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']",NaN
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",Posted 1 month ago,12,1,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail...",NaN
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",Posted 23 days ago,74,2,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co...",NaN
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",Posted 1 month ago,50,4,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']",NaN
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",Posted 3 days ago,32,1,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",Posted 4 days ago,Be the First to Apply,NaN,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito...",NaN
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",Posted 2 days ago,Be the First to Apply,NaN,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie...",NaN
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",Posted 2 months ago,49,1,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas...",NaN
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",Posted 13 days ago,81,1,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']",NaN
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",Posted 15 days ago,15,5,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D...",NaN

#check working place.unique.count , remove "Posted" from colomn post_date , remove "be the first to apply" from number of applicants and make it 0
#remove Nan from number of positions and put 0, check career_level, check education, prefered to drop salary but count 1st numb of confidential

In [37]:
print(df['Working_Place'].value_counts())

Working_Place
On-site                        7805
Hybrid                          580
Remote                          520
information technology (it)       9
Information Technology (IT)       5
Marketing                         5
sales                             4
Administration                    4
kuwaitis                          4
Maintenance                       4
Sales                             3
Human Resources (HR)              3
Collection                        2
saudi                             2
Customer Service                  2
Project Management                2
Kitchen                           2
Customer Support                  2
marketing                         2
Business Development              2
Leasing                           1
hospitality                       1
QC                                1
teachers                          1
internship                        1
Graphic Design                    1
dermatology                       1
educator                          1
Legal                             1
Microsoft Office                  1
engineering                       1
Security                          1
hr                                1
icu                               1
Education                         1
Compliance                        1
Design                            1
R&D                               1
Mechanical Engineering            1
Accounting                        1
medical                           1
Name: count, dtype: int64

#replace other values in Working_Place and replace it with onsite

#post date (edit)

In [40]:
# Remove "Posted" from the 'post_date' column
df['Post_Date'] = df['Post_Date'].str.replace('Posted', '', regex=False)

df

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills,Gender
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",27 days ago,48,1,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']",NaN
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",1 month ago,12,1,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail...",NaN
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",23 days ago,74,2,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co...",NaN
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",1 month ago,50,4,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']",NaN
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",3 days ago,32,1,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",4 days ago,Be the First to Apply,NaN,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito...",NaN
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",2 days ago,Be the First to Apply,NaN,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie...",NaN
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",2 months ago,49,1,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas...",NaN
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",13 days ago,81,1,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']",NaN
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",15 days ago,15,5,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D...",NaN

In [41]:
# Remove "be the first to apply" from 'Number_of_Applicants' and replace with 0
df['Number_of_Applicants'] = df['Number_of_Applicants'].replace('Be the First to Apply', '0')

df

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills,Gender
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",27 days ago,48,1,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']",NaN
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",1 month ago,12,1,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail...",NaN
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",23 days ago,74,2,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co...",NaN
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",1 month ago,50,4,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']",NaN
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",3 days ago,32,1,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",4 days ago,0,NaN,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito...",NaN
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",2 days ago,0,NaN,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie...",NaN
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",2 months ago,49,1,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas...",NaN
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",13 days ago,81,1,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']",NaN
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",15 days ago,15,5,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D...",NaN

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8983 entries, 0 to 8982
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 8983 non-null   object
 1   Working_Hours         8983 non-null   object
 2   Working_Place         8983 non-null   object
 3   Company               7949 non-null   object
 4   Location              8983 non-null   object
 5   Post_Date             8983 non-null   object
 6   Number_of_Applicants  8982 non-null   object
 7   Number_of_Positions   8668 non-null   object
 8   Experience            8983 non-null   object
 9   Career_Level          8983 non-null   object
 10  Education             8983 non-null   object
 11  Salary                8176 non-null   object
 12  Job_Category          8983 non-null   object
 13  Skills                8983 non-null   object
 14  Gender                807 non-null    object
dtypes: object(15)
memory usage: 1.0+ MB

In [47]:
df['Number_of_Positions'] = df['Number_of_Positions'].fillna(1)
df['Number_of_Positions'] = df['Number_of_Positions'].astype(int)

df

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills,Gender
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",27 days ago,48,1,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']",NaN
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",1 month ago,12,1,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail...",NaN
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",23 days ago,74,2,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co...",NaN
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",1 month ago,50,4,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']",NaN
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",3 days ago,32,1,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",4 days ago,0,0,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito...",NaN
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",2 days ago,0,0,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie...",NaN
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",2 months ago,49,1,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas...",NaN
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",13 days ago,81,1,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']",NaN
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",15 days ago,15,5,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D...",NaN

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8983 entries, 0 to 8982
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 8983 non-null   object
 1   Working_Hours         8983 non-null   object
 2   Working_Place         8983 non-null   object
 3   Company               7949 non-null   object
 4   Location              8983 non-null   object
 5   Post_Date             8983 non-null   object
 6   Number_of_Applicants  8982 non-null   object
 7   Number_of_Positions   8983 non-null   int64
 8   Experience            8983 non-null   object
 9   Career_Level          8983 non-null   object
 10  Education             8983 non-null   object
 11  Salary                8176 non-null   object
 12  Job_Category          8983 non-null   object
 13  Skills                8983 non-null   object
 14  Gender                807 non-null    object
dtypes: int64(1), object(14)
memory usage: 1.0+ MB

In [49]:
print(df['Career_Level'].value_counts())

Career_Level
Experienced (Non-Manager)                      5501
Entry Level (Junior Level / Fresh Grad)        2098
Manager                                        1100
Senior Management (CEO, GM, Director, Head)     167
Not Specified                                    78
Student (Undergrad / Postgrad)                   39
Name: count, dtype: int64

#take females and males preferred to gender

In [50]:
print(df['Salary'].value_counts())

Salary
Confidential                                      5607
Males Preferred                                    118
Females Preferred                                   60
Confidential, Bonus                                 52
Confidential, Commission                            50
                                                  ...
Confidential, Attractive Package                     1
6000 To 6500 EGP Per Month                           1
5000 To 10000 USD Per Month                          1
Confidential, Depend On Interview                    1
10000 To 30000 EGP Per Month, Bonus Commission       1
Name: count, Length: 1296, dtype: int64

In [51]:
print(df['Education'].value_counts())

Education
Bachelor'S Degree              5180
Not Specified                  3725
High School (Or Equivalent)      32
Master'S Degree                  29
Diploma                          11
MBA                               4
College Diploma                   2
Name: count, dtype: int64

In [52]:
df

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills,Gender
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",27 days ago,48,1,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']",NaN
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",1 month ago,12,1,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail...",NaN
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",23 days ago,74,2,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co...",NaN
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",1 month ago,50,4,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']",NaN
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",3 days ago,32,1,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",4 days ago,0,0,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito...",NaN
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",2 days ago,0,0,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie...",NaN
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",2 months ago,49,1,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas...",NaN
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",13 days ago,81,1,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']",NaN
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",15 days ago,15,5,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D...",NaN

# Drop duplicates

In [53]:
df = df.drop_duplicates()
df

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills,Gender
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",27 days ago,48,1,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']",NaN
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",1 month ago,12,1,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail...",NaN
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",23 days ago,74,2,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co...",NaN
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",1 month ago,50,4,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']",NaN
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",3 days ago,32,1,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",4 days ago,0,0,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito...",NaN
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",2 days ago,0,0,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie...",NaN
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",2 months ago,49,1,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas...",NaN
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",13 days ago,81,1,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']",NaN
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",15 days ago,15,5,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D...",NaN

In [54]:
df["Gender"] = df["Gender"].fillna("both")
df

<ipython-input-54-96504da9ca49>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].fillna("both")

,Title,Working_Hours,Working_Place,Company,Location,Post_Date,Number_of_Applicants,Number_of_Positions,Experience,Career_Level,Education,Salary,Job_Category,Skills,Gender
0,School Head of Admissions,Full Time,On-site,Egypt Education Platform,"Riyadh, Saudi Arabia",27 days ago,48,1,3 To 10 Years,Experienced (Non-Manager),Not Specified,Confidential,Marketing/PR/Advertising,"['Marketing', 'School', 'Education']",both
1,Senior Backend Developer,Full Time,Hybrid,RocketDevs,"Cairo, Egypt",1 month ago,12,1,More Than 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,IT/Software Development,"['Software Development', 'Ruby', 'Ruby on Rail...",both
2,Civil Engineer,Full Time,On-site,SAAB Engineering Consulating Office,"Agouza, Giza",23 days ago,74,2,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,8000 To 12000 EGP Per Month,Engineering - Construction/Civil/Architecture,"['AutoCAD', 'Civil Engineering', 'Design', 'Co...",both
3,Senior Tendering Engineer,Full Time,On-site,REDCON Construction Co. S.A.E,"Cairo, Egypt",1 month ago,50,4,5 To 8 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Engineering - Construction/Civil/Architecture,"['Civil', 'tender', 'Engineering', 'Tendering']",both
4,Senior Android Developer,Full Time,Hybrid,Fixed Solutions,"Cairo, Egypt",3 days ago,32,1,3 To 5 Years,Experienced (Non-Manager),Not Specified,Confidential,IT/Software Development,"['Android', 'APIs', 'Software Engineering', 'S...",both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8978,Content & Digital Marketing Executive,Full Time,On-site,Quintessentially Egypt [Global Lifestyles SAE],"Maadi, Cairo",4 days ago,0,0,2 To 4 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Writing/Editorial,"['Content Writing', 'Creative Writing', 'Edito...",both
8979,Application Tester - 6 Months (Extendable),Full Time,information technology (it),People Dynamics,"Doha, Qatar",2 days ago,0,0,Not Specified,Not Specified,Not Specified,Confidential,IT/Software Development,"['information technology (it)', 'computer scie...",both
8980,Senior Front End Developer (Vuejs),Full Time,Hybrid,Finiex Soft,"Fleming, Alexandria",2 months ago,49,1,3 To 5 Years,Experienced (Non-Manager),Bachelor'S Degree,Confidential,Business Development,"['CSS', 'Computer Science', 'JavaScript', 'Sas...",both
8981,Maintenance Mechanical Engineer,Full Time,On-site,Koning Food Industries,"10th of Ramadan City, Sharqia",13 days ago,81,1,2 To 4 Years,Experienced (Non-Manager),Not Specified,Confidential,Engineering - Mechanical/Electrical,"['Maintenance', 'Mechanical Engineering']",both
8982,Executive Sales Representative,Full Time,On-site,Mannasat Egypt,"Hadayek Alahram, Giza",15 days ago,15,5,3 To 7 Years,Experienced (Non-Manager),Bachelor'S Degree,"10000 To 30000 EGP Per Month, Bonus Commission",Business Development,"['Sales', 'Executive', 'business', 'Business D...",both

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8259 entries, 0 to 8982
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 8259 non-null   object
 1   Working_Hours         8259 non-null   object
 2   Working_Place         8259 non-null   object
 3   Company               7314 non-null   object
 4   Location              8259 non-null   object
 5   Post_Date             8259 non-null   object
 6   Number_of_Applicants  8258 non-null   object
 7   Number_of_Positions   8259 non-null   int64
 8   Experience            8259 non-null   object
 9   Career_Level          8259 non-null   object
 10  Education             8259 non-null   object
 11  Salary                7514 non-null   object
 12  Job_Category          8259 non-null   object
 13  Skills                8259 non-null   object
 14  Gender                8259 non-null   object
dtypes: int64(1), object(14)
memory usage: 1.0+ MB

In [57]:
df["Number_of_Applicants"] = df["Number_of_Applicants"].fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8259 entries, 0 to 8982
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 8259 non-null   object
 1   Working_Hours         8259 non-null   object
 2   Working_Place         8259 non-null   object
 3   Company               7314 non-null   object
 4   Location              8259 non-null   object
 5   Post_Date             8259 non-null   object
 6   Number_of_Applicants  8259 non-null   object
 7   Number_of_Positions   8259 non-null   int64
 8   Experience            8259 non-null   object
 9   Career_Level          8259 non-null   object
 10  Education             8259 non-null   object
 11  Salary                7514 non-null   object
 12  Job_Category          8259 non-null   object
 13  Skills                8259 non-null   object
 14  Gender                8259 non-null   object
dtypes: int64(1), object(14)
memory usage: 1.0+ MB

<ipython-input-57-b54381ff6912>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Number_of_Applicants"] = df["Number_of_Applicants"].fillna(0)

#experience column separate it into 2 columns from and to

#skills column change from list to text
#check for duplicated skills that have same meaning
#sales and sales target fy "s" gya out of nowhere !!!!!!